title: Introduction to Bonsai
description: A course on Visual Reactive Programming developed by NeuroGEARS Ltd.
funding: This course was prepared and developed for the European Social Club 2025 meeting.
funding_logo: esc
funding_url: https://esc-coimbra2025.cnc.uc.pt/
google_analytics:
theme: minima
baseurl: "/esc-2025"
docsurl: "https://bonsai-rx.org/docs"

github_username:  neurogears
mastodon:
  - username: bonsai
    instance: neuromatch.social

kramdown:
  parse_block_html: true

plugins:
  - jekyll-seo-tag

include:
  - _pages
  - _slides

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"

header_pages:
  - _pages/neurokit.md
  - _pages/slides.md
  - _pages/worksheets.md

collections:
  # Ideally we would use collections for slides but this
  # breaks reveal.js markdown processing because of issue:
  # https://github.com/jekyll/jekyll/issues/6209
  # slides:
  #   output: true
  #   permalink: /:collection/:path/
  
  worksheets:
    output: true
    permalink: /:collection/:path/
